name: Flutter Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.2'

      - name: Install dependencies
        run: flutter pub get

      - name: Build release APK
        run: flutter build apk --release

      - name: Rename APK
        run: |
          mkdir -p build/app/outputs/renamed-apk
          mv build/app/outputs/flutter-apk/app-release.apk build/app/outputs/renamed-apk/silent_snitch.apk

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: release-apk
          path: build/app/outputs/renamed-apk/silent_snitch.apk

      - name: Upload Release APK to GitHub Releases
        uses: softprops/action-gh-release@v1
        with:
          files: build/app/outputs/renamed-apk/silent_snitch.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
